### ISSUE TITLE
Please do not pin dependancies as it makes upgrading due to security issues hard

### ISSUE THREAD

**Issue by sawilde** [chrisburnell/eleventy-cache-webmentions#1]
Getting the following alert

![image](https://user-images.githubusercontent.com/297165/192897473-585964ca-aced-47dc-bb1d-18b850bc2f98.png)

which dependabot cannot handle

https://github.com/chrisburnell/eleventy-cache-webmentions/blob/571bda3e18d39fad2344b1669fd1e8937763f030/package.json#L21

should use a ^ like the other dependancies in the package

```json
   "node-fetch": "^2.6.5", 
```

There are workarounds, so I am not blocked but it is easier if the package maintainer sets up their package up correctly

Nb: It is okay to pin devDependancies

**Comment by chrisburnell** [comment]
Hey @sawilde,

Thanks for the report! After going down a small rabbit hole, learning a bit more about how dependencies work (I tip my hat to you!), I've unpinned the `node-fetch` dependency.

This is reflected in the latest version, `1.0.1`.

Thank you!
